/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 16 18:50:43 GMT 2020
 */

package TCG;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import TCG.WBS;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WBS_ESTest extends WBS_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WBS wBS0 = new WBS();
      wBS0.update((-541), false, false);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        WBS.launch(1576, true, true, 1576, false, true, 1576, false, true, 1576, true, false, 1576, true, false);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WBS wBS0 = new WBS();
      wBS0.update(7, true, false);
      wBS0.update(7, false, false);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WBS wBS0 = new WBS();
      wBS0.update(4, false, false);
      wBS0.update(1, true, false);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WBS wBS0 = new WBS();
      wBS0.update(2, false, false);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      WBS wBS0 = new WBS();
      wBS0.update(1, true, true);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      WBS wBS0 = new WBS();
      wBS0.update(0, true, true);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        WBS.main(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      WBS wBS0 = new WBS();
      wBS0.update(3, false, false);
  }
}
